services:
  master:
    image: ajosonn/mapreduce:latest
    container_name: mapreduce_master
    command: python -m src.master.server
    ports:
      - "50051:50051"
    networks:
      - mapreduce_net
    environment:
      - PYTHONUNBUFFERED=1

  worker1:
    image: ajosonn/mapreduce:latest
    container_name: mapreduce_worker1
    command: python -m src.worker.client worker1
    depends_on:
      - master
    networks:
      - mapreduce_net
    environment:
      - PYTHONUNBUFFERED=1
      - MASTER_ADDRESS=master:50051

  worker2:
    image: ajosonn/mapreduce:latest
    container_name: mapreduce_worker2
    command: python -m src.worker.client worker2
    depends_on:
      - master
    networks:
      - mapreduce_net
    environment:
      - PYTHONUNBUFFERED=1
      - MASTER_ADDRESS=master:50051

  worker3:
    image: ajosonn/mapreduce:latest
    container_name: mapreduce_worker3
    command: python -m src.worker.client worker3
    depends_on:
      - master
    networks:
      - mapreduce_net
    environment:
      - PYTHONUNBUFFERED=1
      - MASTER_ADDRESS=master:50051

networks:
  mapreduce_net:
    driver: bridge